-- Ordered alphabetically under Character, Effect, Stand, then Other groups
jojoker.joker_order = {
    -- Characters
    "baron_zeppeli",
    "caesar",
    "danny",
    "danny_sbr",
    "esidisi",
    "george_joestar",
    "green_baby",
    "joseph_joestar",
    "josuke_higashikata_jjl",
    "kars_stopped_thinking",
    "kars_ultimate_lifeform",
    "leaky_eye_luca",
    "ndoul",
    "nypd",
    "shizuka",
    "speedwagon",
    "speedwagon_bt",
    "straizo",
    "suzi_q",
    "zombies",

    -- Effects
    "epitaph",
    "german_engineering",
    "higashikata_house",
    "higashikata_fruit_parlor",
    "the_fifth_lesson",
    "voice_of_love",

    -- Stands
    "bad_company",
    "chocolate_disco",
    "crazy_diamond",
    "dragons_dream",
    "gold_experience",
    "gold_experience_requiem",
    "goo_goo_dolls",
    "grateful_dead",
    "hey_ya",
    "i_am_a_rock",
    "king_crimson",
    "made_in_heaven",
    "magician_red",
    "mandom",
    "milagro_man",
    "oh_lonesome_me",
    "paper_moon_king",
    "red_hot_chili_pepper",
    "sex_pistols",
    "smooth_operator",
    "soft_and_wet",
    "spice_girl",
    "star_platinum",
    "sticky_fingers",
    "stone_free",
    "superfly",
    "survivor",
    "tattoo_you",
    "the_hand",
    "the_lovers",
    "wheel_of_fortune",
    "yellow_temperance",

    -- Other
}