-- Ordered alphabetically under Character, Effect, Stand, then Other groups
jojoker.joker_order = {
    -- Characters
    "baron_zeppeli",
    "caesar",
    "danny",
    "danny_sbr",
    "dario_brando",
    "erina",
    "esidisi",
    "george_joestar",
    "jonathan_joestar",
    "joseph_joestar",
    "josuke_higashikata_jjl",
    "kars_stopped_thinking",
    "kars_ultimate_lifeform",
    "leaky_eye_luca",
    "ndoul",
    "nypd",
    "old_joseph_joestar",
    "pucci",
    "santana",
    "savage_garden",
    "shizuka",
    "speedwagon",
    "speedwagon_bt",
    "straizo",
    "stroheim",
    "stroheim_german_engineering",
    "suzi_q",
    "yoshikage_kira",
    "zombies",
    
    -- Effects
    "epitaph",
    "german_engineering",
    "higashikata_house",
    "higashikata_fruit_parlor",
    "the_fifth_lesson",
    "the_true_mans_world",
    "turbo_eyes",
    "voice_of_love",
    
    -- Stands
    "anubis",
    "baby_face",
    "bad_company",
    "burning_down_the_house",
    "california_king_bed",
    "cheap_trick",
    "chocolate_disco",
    "civil_war",
    "crazy_diamond",
    "doctor_wu",
    "dragons_dream",
    "foo_fighters",
    "gold_experience",
    "gold_experience_requiem",
    "goo_goo_dolls",
    "grateful_dead",
    "green_green_grass_of_home",
    "hey_ya",
    "i_am_a_rock",
    "king_crimson",
    "made_in_heaven",
    "magician_red",
    "mandom",
    "milagro_man",
    "moody_blues",
    "oh_lonesome_me",
    "paper_moon_king",
    "red_hot_chili_pepper",
    "sethan",
    "sex_pistols",
    "smooth_operator",
    "soft_and_wet",
    "spice_girl",
    "star_platinum",
    "sticky_fingers",
    "stone_free",
    "superfly",
    "survivor",
    "tattoo_you",
    "the_hand",
    "the_lovers",
    "wheel_of_fortune",
    "white_snake",
    "wonder_of_u",
    "yellow_temperance",

    -- Other
}