[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Localization color
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "legendary = G.C.RARITY[4],"
position = "after"
payload = "joker_stand = G.C.RARITY['stand'], joker_user = G.C.RARITY['user'], joker_effect = G.C.RARITY['effect'],"
match_indent = true

# Jojoker Only functionality
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if v.yes_pool_flag and not G.GAME.pool_flags[v.yes_pool_flag] then add = nil end"
position = "after"
payload = '''
if v.set == 'Joker' and not v.part and jojoker_config and jojoker_config.jojoker_only then add = nil end
if v.set == 'Joker' and v.part and not get_part_allowed(v) then add = nil end
'''
match_indent = true

# Descriptions
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
if main_end then 
    desc_nodes[#desc_nodes+1] = main_end 
end
'''
position = "after"
payload = '''
if (_c.set == 'Item') and _c.jojoker_add_desc then
  localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = loc_vars}
end
'''
match_indent = true

# Card Effect Divider
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "elseif part.control.X or part.control.B then"
position = "before"
payload = '''
elseif part.control.br then
  local height = 0.05
  local gaps = 0.2
  local mid = 0.15
  local sides = (tonumber(part.control.br) - gaps*2 - mid) / 2
  -- spacing
  args.nodes[#args.nodes+1] = {{n=G.UIT.R, config={align = "cm", minh = height}, nodes={}}}
  if sides < gaps then
    args.nodes[#args.nodes+1] = {{n=G.UIT.C, config={align = "cm", colour = G.C.UI.TRANSPARENT_DARK, minw = tonumber(part.control.br), minh = height}}}
  else
    local temp_nodes = {{n=G.UIT.C, config={align = "cm", colour = G.C.UI.TRANSPARENT_DARK, minw = sides, minh = height}, nodes={}},
                        {n=G.UIT.C, config={align = "cm", minw = gaps}, nodes={}},
                        {n=G.UIT.C, config={align = "cm", colour = G.C.UI.TEXT_INACTIVE, minw = mid, minh = height}, nodes={}},
                        {n=G.UIT.C, config={align = "cm", minw = gaps}, nodes={}},
                        {n=G.UIT.C, config={align = "cm", colour = G.C.UI.TRANSPARENT_DARK, minw = sides, minh = height}, nodes={}}}
    args.nodes[#args.nodes+1] = {{n=G.UIT.R, config={align = "cm", minw = tonumber(part.control.br)}, nodes=temp_nodes}}
  end
'''
match_indent = true

# Shortcut Pareidolia Four Fingers effects
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = '''function find_joker(name, non_debuff)'''
position = 'after'
payload = '''
if name == "Shortcut" then
  local shortcut = find_joker("jojoker_Shortcut")
  local joker_one = find_joker("the_fifth_lesson")
  return (next(shortcut) and shortcut) or (next(joker_one) and joker_one) or {}
elseif name == "Pareidolia" then
  local shortcut = find_joker("jojoker_Pareidolia")
  local joker_one = find_joker("paper_moon_king")
  return (next(shortcut) and shortcut) or (next(joker_one) and joker_one) or {}
elseif name == "Four Fingers" then
  local shortcut = find_joker("jojoker_Four_Fingers")
  local joker_one = find_joker("josuke_higashikata_jjl")
  return (next(shortcut) and shortcut) or (next(joker_one) and joker_one) or {}
elseif name == "Smeared Joker" then
  local smeared = find_joker("jojoker_Smeared_Joker")
  local joker_one = find_joker("ndoul")
  return (next(smeared) and smeared) or (next(joker_one) and joker_one) or {}
elseif name == "jojoker_Pareidolia" then
  name = "Pareidolia"
elseif name == "jojoker_Four_Fingers" then
  name = "Four Fingers"
elseif name == "jojoker_Smeared_Joker" then
  name = "Smeared Joker"
end
'''
match_indent = true