[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Scan functionality
## Scan Functionality 1
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "function Game:update_selecting_hand(dt)"
position = "after"
payload = '''
    if not self.scan_view and type(create_scan_cardarea) == "function" then
      self.scan_view = create_scan_cardarea()
    elseif self.scan_view then
      update_scan_cardarea(self.scan_view)
    end
'''
match_indent = true

## Scan Functionality 2
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "if self.config.type == 'hand' or self.config.type == 'play' or self.config.type == 'title' or self.config.type == 'voucher' then"
position = "at"
payload = "if self.config.type == 'hand' or self.config.type == 'scan' or self.config.type == 'play' or self.config.type == 'title' or self.config.type == 'voucher' then"
match_indent = true
overwrite = true

## Scan Functionality 3
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "if self.config.type == 'hand' and not (G.STATE == G.STATES.TAROT_PACK or G.STATE == G.STATES.SPECTRAL_PACK or G.STATE == G.STATES.PLANET_PACK or G.STATE == G.STATES.SMODS_BOOSTER_OPENED) then"
position = "at"
payload = "if self.config.type == 'scan' or self.config.type == 'hand' and not (G.STATE == G.STATES.TAROT_PACK or G.STATE == G.STATES.SPECTRAL_PACK or G.STATE == G.STATES.PLANET_PACK or G.STATE == G.STATES.SMODS_BOOSTER_OPENED) then"
match_indent = true
overwrite = true

## Scan Functionality 4
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "function Game:update_round_eval(dt)"
position = "after"
payload = '''
    if G.scan_view then hide_scan_cardarea() end
'''
match_indent = true

## Scan Functionality 5
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "-- TARGET: add your own CardAreas for playing card evaluation"
position = "after"
payload = '''
if G.scan_view and G.scan_view.cards then
    t[#t+1] = G.scan_view
end
'''
match_indent = true

## Scan Functionality 6
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "local config = {}"
position = "before"
payload = '''
if card.area == G.scan_view then
    y_off = -0.05*G.CARD_H
    card_aligned = 'tm'
end
'''
match_indent = true

## Transform back to The Fool on shop enter
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.STATE = G.STATES.SHOP"
position = "after"
payload = '''
    -- This runs immediately when the player clicks "Cash Out"
    for i = 1, #G.jokers.cards do
        local current_joker = G.jokers.cards[i]
        -- Adding a check to ensure the card exists
        if current_joker and current_joker.ability and current_joker.ability.extra and current_joker.ability.extra.is_the_fool then
            sendDebugMessage("JoJoker: Converting " .. current_joker.ability.name .. " back to The Fool")
            -- Ensure transform_joker is a globally accessible function in your mod
            transform_joker(current_joker, 'j_jojoker_the_fool')
            G.E_MANAGER:add_event(Event(
            {
                func = function() card_eval_status_text(current_joker, 'extra', nil, nil, nil, {message = localize('sound_reverting')}); return true
                end
            }))
        end
    end
'''
match_indent = true

## Increase booster pack contents (Paisley Park)
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "booster_obj = self.config.center"
position = "after"
payload = '''
if G.GAME.extra_booster_picks and G.GAME.extra_booster_picks > 0 then
  self.ability.extra = self.ability.extra + G.GAME.extra_booster_picks
end
'''
match_indent = true

## Card duplication event (Kiss)
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "function copy_card(other, new_card, card_scale, playing_card, strip_edition)"
position = "after"
payload = '''
if type(jojoker_handle_card_copy) == "function" then
  jojoker_handle_card_copy(other, new_card, card_scale)
end
'''
match_indent = true